version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  
volumes:
  postgres_data:
