version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  

  backup:
    image: ubuntu:latest
    container_name: postgres_backup
    volumes:
      - pgbackups:/backups
      - ~/backup-scripts:/scripts
    depends_on:
      - postgres
    entrypoint: ["/scripts/backup_entrypoint.sh"]
    restart: always  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
  pgbackups:
   driver: local
   driver_opts:
      type: none
      o: bind
      device: /var/www/backupdbtpmobile
