version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tp_db
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backup:
    image: tiredofit/postgresql
    container_name: tp_db_backup
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=tp_db
      - POSTGRES_USER=tp_user
      - POSTGRES_PASSWORD=tp_password
      - BACKUP_TYPE=sql
      - BACKUP_TIME=daily
      - BACKUP_RETENTION=7
    volumes:
      - pgbackups:/backup
    depends_on:
      - postgres
volumes:
  postgres_data:
  pgbackups:
