version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  

  redis:
    image: redis:7 
    container_name: tp_redis
    ports:
      - '6379:6379' 
    volumes:
      - redis_data:/data 
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

volumes:
  postgres_data:
  redis_data: