version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tp_db
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  # Thêm chính sách khởi động lại

  backup:
    image: ubuntu:latest
    container_name: postgres_backup
    volumes:
      - pgbackups:/backups
      - ~/backup-scripts:/scripts
    depends_on:
      - postgres
    entrypoint: ["/scripts/backup_entrypoint.sh"]
    restart: always  # Thêm chính sách khởi động lại
volumes:
  postgres_data:
  pgbackups: