version: '3.7'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: tp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tp_db
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: